
name: Hello World

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: |
          echo "Hello World"
          echo "I am learning github workflows"
          echo "This is running on ubuntu-latest"
