name: PR Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run test
        run: echo "This is pull request!"

      - name: Next test
        run: echo "This test reach this line!"
