
name: Run exercises path

on:
  push:
    paths: "exercises/01_classes/**"

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: run_script
        run: |
          python exercises/01_classes/class1.py
          echo "this python scripts is working"

